# Generated by Django 3.2.3 on 2021-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_str', models.CharField(max_length=9999)),
                ('data_source', models.FileField(upload_to='app/uploads')),
                ('dimension_name', models.CharField(max_length=9999)),
                ('dimension_lookup_attributes', models.CharField(max_length=9999)),
            ],
        ),
    ]
